### ISSUE TITLE
Bottle release

### ISSUE THREAD

**Issue by ncihnegn** [llvm-hs/homebrew-llvm#16]
Building LLVM from source is time consuming.
I built a minimal LLVM9 bottle here: https://github.com/ncihnegn/homebrew-formulae.

**Comment by tmcdonell** [comment]
Why not submit a PR to do this here? Does it need to be the minimal bottle?

**Comment by ncihnegn** [comment]
GitHub tokens expire in one hour. So a full build is out of the question.

**Comment by tmcdonell** [comment]
Actually this was still useful. Now that I know we aren't limited to hosting the binary files on Bintray (what homebrew uses) I can include bottles with each release.

**Comment by FranklinChen** [comment]
```
➜  ~ brew install llvm-10
==> Installing llvm-10 from llvm-hs/llvm
==> Downloading https://github.com/llvm-hs/homebrew-llvm/releases/download/v10.0

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "llvm-10"
Download failed: https://github.com/llvm-hs/homebrew-llvm/releases/download/v10.0.0/llvm-10-10.0.0.mojave.bottle.tar.gz
```

**Comment by tmcdonell** [comment]
@FranklinChen try again? I edited the name directly on GitHub but if that doesn't work I'll re-upload with the correct name.

**Comment by FranklinChen** [comment]
Installed OK now on my Catalina Mac.

**Comment by tmcdonell** [comment]
Brilliant! Thanks (:
