### ISSUE TITLE
brew install llvm-hs/homebrew-llvm/llvm-4.0 fails

### ISSUE THREAD

**Issue by rzil** [llvm-hs/homebrew-llvm#4]
$ brew install llvm-hs/homebrew-llvm/llvm-4.0
==> Installing llvm-4.0 from llvm-hs/llvm
==> Downloading http://releases.llvm.org/4.0.0/llvm-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/cfe-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0--clang-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/libcxx-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0--libcxx-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/lld-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0--lld-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/polly-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0--polly-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/clang-tools-extra-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0--clang-tools-extra-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/openmp-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0--openmp-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/libcxx-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0--libcxx-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/libunwind-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0--libunwind-4.0.0.tar.xz
==> Downloading http://releases.llvm.org/4.0.0/compiler-rt-4.0.0.src.tar.xz
Already downloaded: /Users/ruben/Library/Caches/Homebrew/llvm-4.0--compiler-rt-4.0.0.tar.xz
==> cmake /private/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFI
==> cmake --build .
Last 15 lines from /Users/ruben/Library/Logs/Homebrew/llvm-4.0/02.cmake:
[  6%] Building CXX object projects/libcxx/lib/CMakeFiles/cxx_objects.dir/__/src/typeinfo.cpp.o
cd /tmp/llvm-4.0-20170411-14039-5hz8ki/projects/libcxx/lib && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -D_DEBUG -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-4.0-20170411-14039-5hz8ki/projects/libcxx/lib -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/lib -I/tmp/llvm-4.0-20170411-14039-5hz8ki/include -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/include -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/include  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers  -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -Werror=date-time -std=c++11   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12    -UNDEBUG -std=c++11 -nostdinc++ -fvisibility-inlines-hidden -Wall -Wextra -W -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wno-user-defined-literals -Wno-covered-switch-default -Wno-error -fPIC -o CMakeFiles/cxx_objects.dir/__/src/typeinfo.cpp.o -c /tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/src/typeinfo.cpp
[  6%] Building CXX object projects/libcxx/lib/CMakeFiles/cxx_objects.dir/__/src/utility.cpp.o
cd /tmp/llvm-4.0-20170411-14039-5hz8ki/projects/libcxx/lib && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -D_DEBUG -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-4.0-20170411-14039-5hz8ki/projects/libcxx/lib -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/lib -I/tmp/llvm-4.0-20170411-14039-5hz8ki/include -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/include -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/include  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers  -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -Werror=date-time -std=c++11   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12    -UNDEBUG -std=c++11 -nostdinc++ -fvisibility-inlines-hidden -Wall -Wextra -W -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wno-user-defined-literals -Wno-covered-switch-default -Wno-error -fPIC -o CMakeFiles/cxx_objects.dir/__/src/utility.cpp.o -c /tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/src/utility.cpp
[  6%] Building CXX object projects/libcxx/lib/CMakeFiles/cxx_objects.dir/__/src/valarray.cpp.o
cd /tmp/llvm-4.0-20170411-14039-5hz8ki/projects/libcxx/lib && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -D_DEBUG -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-4.0-20170411-14039-5hz8ki/projects/libcxx/lib -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/lib -I/tmp/llvm-4.0-20170411-14039-5hz8ki/include -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/include -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/include  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers  -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -Werror=date-time -std=c++11   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12    -UNDEBUG -std=c++11 -nostdinc++ -fvisibility-inlines-hidden -Wall -Wextra -W -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wno-user-defined-literals -Wno-covered-switch-default -Wno-error -fPIC -o CMakeFiles/cxx_objects.dir/__/src/valarray.cpp.o -c /tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/src/valarray.cpp
[  6%] Building CXX object projects/libcxx/lib/CMakeFiles/cxx_objects.dir/__/src/variant.cpp.o
cd /tmp/llvm-4.0-20170411-14039-5hz8ki/projects/libcxx/lib && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -D_DEBUG -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-4.0-20170411-14039-5hz8ki/projects/libcxx/lib -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/lib -I/tmp/llvm-4.0-20170411-14039-5hz8ki/include -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/include -I/tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/include  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers  -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -Werror=date-time -std=c++11   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12    -UNDEBUG -std=c++11 -nostdinc++ -fvisibility-inlines-hidden -Wall -Wextra -W -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wno-user-defined-literals -Wno-covered-switch-default -Wno-error -fPIC -o CMakeFiles/cxx_objects.dir/__/src/variant.cpp.o -c /tmp/llvm-4.0-20170411-14039-1pwbg1d/llvm-4.0.0.src/projects/libcxx/src/variant.cpp
[  6%] Built target cxx_objects
[  6%] Linking CXX static library ../../libLLVMDebugInfoPDB.a
cd /tmp/llvm-4.0-20170411-14039-5hz8ki/lib/DebugInfo/PDB && /usr/local/Cellar/cmake/3.7.2_1/bin/cmake -P CMakeFiles/LLVMDebugInfoPDB.dir/cmake_clean_target.cmake
cd /tmp/llvm-4.0-20170411-14039-5hz8ki/lib/DebugInfo/PDB && /usr/local/Cellar/cmake/3.7.2_1/bin/cmake -E cmake_link_script CMakeFiles/LLVMDebugInfoPDB.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -no_warning_for_no_symbols -o ../../libLLVMDebugInfoPDB.a          CMakeFiles/LLVMDebugInfoPDB.dir/GenericError.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/IPDBSourceFile.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDB.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBContext.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBExtras.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBInterfaceAnchors.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbol.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolAnnotation.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolBlock.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolCompiland.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolCompilandDetails.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolCompilandEnv.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolCustom.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolData.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolExe.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolFunc.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolFuncDebugEnd.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolFuncDebugStart.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolLabel.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolPublicSymbol.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolThunk.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeArray.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeBaseClass.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeBuiltin.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeCustom.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeDimension.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeEnum.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeFriend.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeFunctionArg.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeFunctionSig.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeManaged.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypePointer.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeTypedef.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeUDT.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeVTable.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeVTableShape.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolUnknown.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolUsingNamespace.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymDumper.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/DbiStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/DbiStreamBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/EnumTables.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/GlobalsStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/GSI.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/Hash.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/InfoStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/InfoStreamBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/ModInfo.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/ModStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/NameHashTable.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/NameMap.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/NameMapBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/PDBFile.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/PDBFileBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/PublicsStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/RawError.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/RawSession.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/SymbolStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/TpiHashing.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/TpiStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Raw/TpiStreamBuilder.cpp.o 
[  6%] Built target LLVMDebugInfoPDB
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/llvm-hs/homebrew-llvm/issues

**Comment by tmcdonell** [comment]
Do you have a previous install of Homebrew's `llvm` formula? Try `brew unlink llvm` (or `brew rm llvm` to be safe) first. LLVM _must_ be built with the system compiler, otherwise you'll get weird failures like this.

If that does not work, please upload the full log as a gist by following the instructions [here](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#create-an-issue) (the above does not actually include the error).

It's probably also useful to know what OS version you are on, and the output of `which clang` and `clang --version`, etc.

**Comment by rzil** [comment]
I did have a previous install of llvm but I removed it beforehand. I followed your instructions and posted a new issues here
https://github.com/Homebrew/homebrew-core/issues/12301

**Comment by tmcdonell** [comment]
Oh, I meant the instructions to upload the gist logs. Sorry I should have been more specific.

Probably the homebrew/core folks don't want to be bothered by us...

**Comment by rzil** [comment]
Good point.

macOS 10.12.4

Apple LLVM version 8.1.0 (clang-802.0.41)

https://gist.github.com/4e42ceb9ac69eb515db042886d09fb82

**Comment by tmcdonell** [comment]
Can you try for me `brew edit llvm-4.0` and comment out [line 128](https://github.com/llvm-hs/homebrew-llvm/blob/master/Formula/llvm-4.0.rb#L128) and see if that works for you?

**Comment by tmcdonell** [comment]
Actually I think I found the problem and pushed a patch. You should by able to just `brew update` and build like normal (but no need to stop your build, if it is already going).

**Comment by rzil** [comment]
> Can you try for me brew edit llvm-4.0 and comment out line 128 and see if that works for you?

This worked. I was already building when you posted last post.

**Comment by tmcdonell** [comment]
Great! (:
