### ISSUE TITLE
Error building a package on mac book pro high Sierra Version 10.13.6

### ISSUE THREAD

**Issue by ROZBEH** [llvm-hs/homebrew-llvm#7]
I am not sure if this is the right place to ask this question, so apologies in case this is not the right place. Here is my question: </br>
I am trying to build [this][1] github repository which is a Microsoft repository for simulating drones and cars. I am doing the build this package based on the instructions in [this][2] link. The problem is when I run the command `./setup.sh`, everything runs smoothly until it gets to `cmake --build .` where the command line stays there for around 1 hour and then throws some error here. Here is what the command line looks like from the time that I run `./setup.sh` to the end. Also, here is the [link][3] to the `./setup.sh`. My problem specifically is: Why `./setup.sh` does not work? I also posted this question on the github of the package.
</br>

    Rouzbehs-MacBook-Pro-2:AirSim Rouzbeh$ ./setup.sh
    + set -e
    +++ dirname ./setup.sh
    ++ cd .
    ++ pwd
    + SCRIPT_DIR=/Users/Rouzbeh/BoxSync/Fall2018/AirSim
    + pushd /Users/Rouzbeh/BoxSync/Fall2018/AirSim
    + downloadHighPolySuv=true
    + [[ '' == \-\-\n\o\-\f\u\l\l\-\p\o\l\y\-\c\a\r ]]
    ++ uname
    + '[' Darwin == Darwin ']'
    + [[ ! -z '' ]]
    + brew tap llvm-hs/homebrew-llvm
    Updating Homebrew...
    ==> Auto-updated Homebrew!
    Updated 2 taps (homebrew/core, homebrew/cask).
    ==> Updated Formulae
    convox                                           jenkins
    brew install llvm-5.0
    ==> Installing llvm-5.0 from llvm-hs/llvm
    ==> Downloading http://releases.llvm.org/5.0.1/llvm-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--5.0.1.tar.xz
    ==> Downloading http://releases.llvm.org/5.0.1/cfe-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--clang--5.0.1.tar.xz
    ==> Downloading http://releases.llvm.org/5.0.1/libcxx-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--libcxx--5.0.1.tar.xz
    ==> Downloading http://releases.llvm.org/5.0.1/lld-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--lld--5.0.1.tar.xz
    ==> Downloading http://releases.llvm.org/5.0.1/polly-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--polly--5.0.1.tar.xz
    ==> Downloading http://releases.llvm.org/5.0.1/clang-tools-extra-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--clang-tools-extra--5.0.1.tar.xz
    ==> Downloading http://releases.llvm.org/5.0.1/openmp-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--openmp--5.0.1.tar.xz
    ==> Downloading http://releases.llvm.org/5.0.1/libcxx-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--libcxx--5.0.1.tar.xz
    ==> Downloading http://releases.llvm.org/5.0.1/libunwind-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--libunwind--5.0.1.tar.xz
    ==> Downloading http://releases.llvm.org/5.0.1/compiler-rt-5.0.1.src.tar.xz
    Already downloaded: /Users/Rouzbeh/Library/Caches/Homebrew/llvm-5.0--compiler-rt--5.0.1.tar.xz
    ==> cmake /private/tmp/llvm-5.0-20180826-50196-5rhe1j/llvm-5.0.1.src -DCMAKE_C_FLAGS_RELEASE=-DND
    ==> cmake --build .
    Last 15 lines from /Users/Rouzbeh/Library/Logs/Homebrew/llvm-5.0/02.cmake:
    [ 94%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_stacktrace_printer.cc.o
    [ 94%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_stoptheworld_mac.cc.o
    [ 94%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_suppressions.cc.o
    [ 94%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_symbolizer.cc.o
    [ 94%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_symbolizer_libbacktrace.cc.o
    [ 94%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_symbolizer_mac.cc.o
    [ 94%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_symbolizer_win.cc.o
    [ 94%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_tls_get_addr.cc.o
    [ 94%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_thread_registry.cc.o
    [ 95%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoTermination.ios.dir/sanitizer_win.cc.o
    [ 95%] Built target RTSanitizerCommonNoTermination.ios
    make[3]: *** [all] Error 2
    make[2]: *** [tools/clang/runtime/compiler-rt-stamps/compiler-rt-build] Error 2
    make[1]: *** [tools/clang/runtime/CMakeFiles/compiler-rt.dir/all] Error 2
    make: *** [all] Error 2
    If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
    https://github.com/llvm-hs/homebrew-llvm/issues

  [1]: https://github.com/Microsoft/AirSim
  [2]: https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md
  [3]: https://github.com/Microsoft/AirSim/blob/master/setup.sh

**Comment by tmcdonell** [comment]
Hi!

uh, I guess this is the right place to submit this issue, since it appears the `brew install llvm-5.0` step is the one which is failing. I don't have much time to look into this at the moment however, so it might be worthwhile to create a ticket on the AirSim repository as well and link back here... perhaps somebody there knows the answer (or can even submit a fix!)

I'll try and take a look at some time but am stretched pretty thinly right now, sorry.

**Comment by ROZBEH** [comment]
Thanks @tmcdonell 
I managed to install it by ```brew install -s llvm --without-compiler-rt```
I also submitted the same issue at Airsim.
